In [48]:
import pandas as pd
import numpy as np

df = pd.read_csv('./diabetes_latih.csv')

X_train = df.values
X_train = np.delete(X_train,8,axis=1)

y_train = df['Outcome'].values

df = pd.read_csv('./diabetes_uji.csv')

X_test = df.values
X_test = np.delete(X_test,8,axis=1)

y_test = df['Outcome'].values

#df.head()
#print(X_train)

[[8.00e+00 1.88e+02 7.80e+01 ... 4.79e+01 1.37e-01 4.30e+01]
 [7.00e+00 1.52e+02 8.80e+01 ... 5.00e+01 3.37e-01 3.60e+01]
 [2.00e+00 9.90e+01 5.20e+01 ... 2.46e+01 6.37e-01 2.10e+01]
 ...
 [5.00e+00 1.21e+02 7.20e+01 ... 2.62e+01 2.45e-01 3.00e+01]
 [1.00e+00 1.26e+02 6.00e+01 ... 3.01e+01 3.49e-01 4.70e+01]
 [1.00e+00 9.30e+01 7.00e+01 ... 3.04e+01 3.15e-01 2.30e+01]]


In [49]:
from sklearn.preprocessing import MinMaxScaler

X_train = MinMaxScaler().fit_transform(X_train)
X_test = MinMaxScaler().fit_transform(X_test)

print(X_train)

[[0.47058824 0.94472362 0.68421053 ... 0.71385991 0.02519214 0.36666667]
 [0.41176471 0.7638191  0.77192982 ... 0.74515648 0.11058924 0.25      ]
 [0.11764706 0.49748744 0.45614035 ... 0.36661699 0.23868488 0.        ]
 ...
 [0.29411765 0.6080402  0.63157895 ... 0.390462   0.07130658 0.15      ]
 [0.05882353 0.63316583 0.52631579 ... 0.4485842  0.11571307 0.43333333]
 [0.05882353 0.46733668 0.61403509 ... 0.45305514 0.10119556 0.03333333]]


In [44]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(hidden_layer_sizes=3,learning_rate_init=0.1,max_iter=100)

clf.fit(X_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=3, learning_rate='constant',
              learning_rate_init=0.1, max_iter=100, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [45]:
y_pred = clf.predict(X_test)

In [46]:
from sklearn.metrics import accuracy_score

round(accuracy_score(y_test,y_pred),3)

0.753

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 9 columns):
Pregnancies                 614 non-null int64
Glucose                     614 non-null int64
BloodPressure               614 non-null int64
SkinThickness               614 non-null int64
Insulin                     614 non-null int64
BMI                         614 non-null float64
DiabetesPedigreeFunction    614 non-null float64
Age                         614 non-null int64
Outcome                     614 non-null int64
dtypes: float64(2), int64(7)
memory usage: 43.3 KB
